Tl podcasts forms
BallantineDigitalMedia/podcasts pull request #4
Opened 2018-08-06 17:50 UTC by TaylorLancaster12

podcasts gem form updates

2018-08-07 20:22 UTC, strikemike2k requested changes

2018-08-07 20:22 UTC, strikemike2k commented on app/views/podcast/episodes/new.html.erb
>  <div class="row admin-container">
There is now an extra closing </div> tag in this file.

2018-08-07 22:08 UTC, TaylorLancaster12 commented on app/views/podcast/episodes/new.html.erb
>  <div class="row admin-container">
Should be good now, removed the bottom tag.

2018-08-08 15:14 UTC, strikemike2k approved these changes

2018-08-08 15:14 UTC, merged